/**
 * Canadian Association of Family Health Support (CAFHS)
 * Canadian Provincial Healthcare & Family Support Directory Dataset
 */

const provincialDirectory = [
  // National Helplines
  {
    id: "nat-988",
    province: "National",
    provinceName: "Canada-Wide",
    category: "mental",
    titleEn: "9-8-8: Suicide Crisis Helpline",
    titleFr: "9-8-8 : Ligne d'aide en cas de crise de suicide",
    descEn: "Canada's national 3-digit suicide prevention and emotional crisis helpline. Free, bilingual, and confidential support by phone or text 24/7.",
    descFr: "Service national d'intervention en cas de crise suicidaire et de détresse émotionnelle. Gratuit, bilingue et confidentiel au téléphone ou par texto 24/7.",
    phone: "9-8-8",
    website: "https://988.ca",
    hours: "24/7 / 365 Days",
    tags: ["Crisis", "Mental Health", "Bilingual", "Free", "Toll-Free"],
    featured: true
  },
  {
    id: "nat-kidshelp",
    province: "National",
    provinceName: "Canada-Wide",
    category: "mental",
    titleEn: "Kids Help Phone / Jeunesse, J'écoute",
    titleFr: "Jeunesse, J'écoute / Kids Help Phone",
    descEn: "24/7 e-mental health service offering free, confidential support to young people in English and French. Text CONNECT to 686868 or call.",
    descFr: "Service d'intervention jeunesse accessible 24/7 en français et anglais. Textez PARLER au 686868 ou appelez.",
    phone: "1-800-668-6868",
    website: "https://kidshelpphone.ca",
    hours: "24/7",
    tags: ["Youth", "Children", "Teens", "Crisis", "Text Support"],
    featured: true
  },
  {
    id: "nat-211",
    province: "National",
    provinceName: "Canada-Wide",
    category: "telehealth",
    titleEn: "2-1-1 Canada: Community & Social Navigation",
    titleFr: "2-1-1 Canada : Navigation sociale et communautaire",
    descEn: "Free, confidential navigation service connecting Canadian families to local food banks, housing, respite care, disability subsidies, and elder support.",
    descFr: "Service de navigation gratuit reliant les familles canadiennes aux banques alimentaires, au logement et aux services aux aînés.",
    phone: "2-1-1",
    website: "https://211.ca",
    hours: "24/7 / Over 150 Languages",
    tags: ["Navigation", "Social Services", "Caregiver", "Housing", "Multilingual"],
    featured: true
  },
  {
    id: "nat-hopeforwellness",
    province: "National",
    provinceName: "Canada-Wide",
    category: "mental",
    titleEn: "Hope for Wellness Indigenous Helpline",
    titleFr: "Ligne d'écoute d'espoir pour le bien-être des Autochtones",
    descEn: "Immediate mental health counseling and crisis intervention to all Indigenous peoples across Canada. Available in English, French, Cree, Ojibway, and Inuktitut.",
    descFr: "Conseil immédiat en santé mentale pour les peuples autochtones. Disponible en français, anglais, cri, ojibwé et inuktitut.",
    phone: "1-855-242-3310",
    website: "https://www.hopeforwellness.ca",
    hours: "24/7",
    tags: ["Indigenous", "Mental Health", "Crisis", "First Nations", "Inuit", "Métis"],
    featured: false
  },

  // Ontario (ON)
  {
    id: "on-health811",
    province: "ON",
    provinceName: "Ontario",
    category: "telehealth",
    titleEn: "Health811 Ontario (Formerly Telehealth Ontario)",
    titleFr: "Santé811 Ontario (anciennement Télésanté)",
    descEn: "Connect with a registered nurse for free, confidential medical advice, symptom assessment, and family physician navigation.",
    descFr: "Parlez gratuitement à un infirmier autorisé pour des conseils médicaux, une évaluation des symptômes et une orientation.",
    phone: "8-1-1 (TTY: 1-866-797-0007)",
    website: "https://health811.ontario.ca",
    hours: "24/7",
    tags: ["Nurse Line", "Medical Advice", "Ontario Health", "Bilingual"],
    featured: true
  },
  {
    id: "on-caregiver",
    province: "ON",
    provinceName: "Ontario",
    category: "caregiver",
    titleEn: "Ontario Caregiver Organization (OCO) Helpline",
    titleFr: "Ligne d'aide de l'Organisme de soutien aux aidants naturels de l'Ontario",
    descEn: "1:1 peer mentorship, 24/7 helpline, and direct access to respite relief funds for family caregivers supporting loved ones across Ontario.",
    descFr: "Mentorat par les pairs, ligne d'écoute 24/7 et accès aux fonds de répit pour les proches aidants en Ontario.",
    phone: "1-833-416-2273",
    website: "https://ontariocaregiver.ca",
    hours: "24/7 Helpline",
    tags: ["Caregiver", "Respite", "Peer Support", "Ontario"],
    featured: true
  },
  {
    id: "on-connex",
    province: "ON",
    provinceName: "Ontario",
    category: "mental",
    titleEn: "ConnexOntario Mental Health & Addictions",
    titleFr: "ConnexOntario Santé mentale et dépendances",
    descEn: "Free, confidential 24/7 navigation to funded youth and adult mental health beds, counseling, and crisis intervention teams.",
    descFr: "Orientation gratuite 24/7 vers les services financés de santé mentale et de dépendances en Ontario.",
    phone: "1-866-531-2600",
    website: "https://www.connexontario.ca",
    hours: "24/7",
    tags: ["Mental Health", "Addictions", "Youth & Adult", "Navigation"],
    featured: false
  },
  {
    id: "on-postpartum",
    province: "ON",
    provinceName: "Ontario",
    category: "maternal",
    titleEn: "Perinatal Mental Health Caregivers Network Ontario",
    titleFr: "Réseau ontarien de santé mentale périnatale",
    descEn: "Specialized clinical therapy pathways, peer doula connections, and new parent depression/anxiety support groups.",
    descFr: "Soutien clinique spécialisé et groupes d'entraide pour la dépression et l'anxiété post-partum des parents.",
    phone: "1-800-668-4680",
    website: "https://www.ontariomidwives.ca",
    hours: "Mon-Fri 8am - 6pm EST",
    tags: ["Maternal", "Postpartum", "Infant", "Doula Support"],
    featured: false
  },
  {
    id: "on-trillium",
    province: "ON",
    provinceName: "Ontario",
    category: "telehealth",
    titleEn: "Trillium Drug Program & Assistive Devices (ADP)",
    titleFr: "Programme de médicaments Trillium et PAAM",
    descEn: "Ontario government subsidies covering high prescription drug costs and specialized pediatric/geriatric medical equipment.",
    descFr: "Subventions de l'Ontario pour les coûts élevés de médicaments sur ordonnance et appareils et accessoires fonctionnels.",
    phone: "1-800-575-5386",
    website: "https://www.ontario.ca/page/get-help-high-prescription-drug-costs",
    hours: "Mon-Fri 8:30am - 5pm EST",
    tags: ["Drug Benefits", "Financial Aid", "Equipment Grants"],
    featured: false
  },

  // British Columbia (BC)
  {
    id: "bc-healthlink",
    province: "BC",
    provinceName: "British Columbia",
    category: "telehealth",
    titleEn: "HealthLink BC (8-1-1)",
    titleFr: "HealthLink BC (8-1-1)",
    descEn: "Speak with registered nurses, dietitians, pharmacists, and exercise physiologists for non-emergency family health support.",
    descFr: "Parlez avec des infirmiers, diététistes et pharmaciens pour des conseils de santé familiale sans frais.",
    phone: "8-1-1 (Translation in 130+ languages)",
    website: "https://www.healthlinkbc.ca",
    hours: "24/7 / Translation available",
    tags: ["Nurse Line", "Dietitian", "Pharmacist", "Multilingual"],
    featured: true
  },
  {
    id: "bc-familycaregivers",
    province: "BC",
    provinceName: "British Columbia",
    category: "caregiver",
    titleEn: "Family Caregivers of British Columbia (FCBC)",
    titleFr: "Aidants familiaux de la Colombie-Britannique",
    descEn: "Dedicated support toll-free line, caregiver coaching, virtual support circles, and education on navigating health authorities.",
    descFr: "Ligne de soutien sans frais, coaching pour aidants, groupes virtuels et éducation pour naviguer le système.",
    phone: "1-877-520-3267",
    website: "https://www.familycaregiversbc.ca",
    hours: "Mon-Fri 8:30am - 4pm PST",
    tags: ["Caregiver", "Senior Care", "Coaching", "BC"],
    featured: true
  },
  {
    id: "bc-foundry",
    province: "BC",
    provinceName: "British Columbia",
    category: "mental",
    titleEn: "Foundry BC Youth & Family Hubs",
    titleFr: "Centres Foundry BC pour jeunes et familles",
    descEn: "Integrated health, mental health, substance use, and peer support for youth aged 12-24 and their families across BC.",
    descFr: "Services intégrés de santé physique et mentale pour les jeunes de 12 à 24 ans et leurs familles en C.-B.",
    phone: "1-833-308-6379",
    website: "https://foundrybc.ca",
    hours: "Drop-in & Virtual Daily",
    tags: ["Youth", "Teens", "Mental Health", "Peer Support", "BC"],
    featured: true
  },
  {
    id: "bc-reproductive",
    province: "BC",
    provinceName: "British Columbia",
    category: "maternal",
    titleEn: "BC Reproductive Mental Health Program",
    titleFr: "Programme de santé mentale génésique de la C.-B.",
    descEn: "Specialized assessment and treatment for individuals experiencing psychiatric disorders during pregnancy and postpartum.",
    descFr: "Évaluation et traitement spécialisés pour la santé mentale pendant la grossesse et la période post-partum.",
    phone: "604-875-2025",
    website: "http://www.bcmhsus.ca",
    hours: "Mon-Fri 8:30am - 4:30pm PST",
    tags: ["Perinatal", "Maternal", "Psychiatry", "Postpartum"],
    featured: false
  },

  // Alberta (AB)
  {
    id: "ab-healthlink",
    province: "AB",
    provinceName: "Alberta",
    category: "telehealth",
    titleEn: "Health Link Alberta (8-1-1)",
    titleFr: "Health Link Alberta (8-1-1)",
    descEn: "24/7 health information, advice from registered nurses, and direct referrals to Alberta Health Services family clinics.",
    descFr: "Information santé 24/7, conseils d'infirmiers et aiguillage vers les cliniques d'Alberta Health Services.",
    phone: "8-1-1",
    website: "https://www.albertahealthservices.ca/811",
    hours: "24/7",
    tags: ["Nurse Line", "Alberta Health", "Triage", "24/7"],
    featured: true
  },
  {
    id: "ab-caregivers",
    province: "AB",
    provinceName: "Alberta",
    category: "caregiver",
    titleEn: "Caregivers Alberta Advisor Line",
    titleFr: "Ligne de conseil des aidants de l'Alberta",
    descEn: "Empowers caregivers with 1-on-1 navigation, the COMPASS for the Caregiver program, and financial subsidy guidance.",
    descFr: "Accompagne les proches aidants albertains avec un soutien individuel et le programme COMPASS.",
    phone: "1-877-453-5088",
    website: "https://www.caregiversalberta.ca",
    hours: "Mon-Fri 8am - 4pm MST",
    tags: ["Caregiver", "Respite", "Alberta", "Workshops"],
    featured: false
  },
  {
    id: "ab-mentalhealth",
    province: "AB",
    provinceName: "Alberta",
    category: "mental",
    titleEn: "Alberta Mental Health Help Line",
    titleFr: "Ligne d'aide en santé mentale de l'Alberta",
    descEn: "Confidential, anonymous service providing crisis intervention, information on family mental health programs, and referrals.",
    descFr: "Service anonyme et confidentiel offrant une intervention de crise et une orientation vers les programmes familiaux.",
    phone: "1-877-303-2642",
    website: "https://www.albertahealthservices.ca",
    hours: "24/7",
    tags: ["Mental Health", "Crisis", "Family Support"],
    featured: false
  },

  // Quebec (QC)
  {
    id: "qc-infossante",
    province: "QC",
    provinceName: "Québec",
    category: "telehealth",
    titleEn: "Info-Santé & Info-Social 8-1-1 Québec",
    titleFr: "Info-Santé et Info-Social 8-1-1 Québec",
    descEn: "Consult a healthcare professional or psychosocial worker directly for triage, pediatric advice, and family crisis support.",
    descFr: "Consultez directement un professionnel de la santé ou un travailleur psychosocial pour un triage et des conseils familiaux.",
    phone: "8-1-1",
    website: "https://www.quebec.ca/sante/trouver-une-ressource/info-sante-811",
    hours: "24/7 / Gratuit et confidentiel",
    tags: ["Info-Santé", "Info-Social", "Bilingue", "Infirmiers"],
    featured: true
  },
  {
    id: "qc-procheaidance",
    province: "QC",
    provinceName: "Québec",
    category: "caregiver",
    titleEn: "L'Appui pour les proches aidants (Info-aidant)",
    titleFr: "L'Appui pour les proches aidants (Service Info-aidant)",
    descEn: "Free, confidential listening, information, and referral service for caregivers of older adults and loved ones in Quebec.",
    descFr: "Service gratuit et confidentiel d'écoute, d'information et de références pour les proches aidants au Québec.",
    phone: "1-855-852-7784",
    website: "https://www.lappui.org",
    hours: "Tous les jours de 8h à 20h",
    tags: ["Proches Aidants", "Aînés", "Répit", "Québec"],
    featured: true
  },
  {
    id: "qc-millejour",
    province: "QC",
    provinceName: "Québec",
    category: "maternal",
    titleEn: "Devenir Parents & Programme SIPPE Québec",
    titleFr: "Services intégrés en périnatalité et petite enfance (SIPPE)",
    descEn: "Early childhood and maternal healthcare tailored for low-income and vulnerable families in CLSC clinics across Quebec.",
    descFr: "Soutien périnatal et petite enfance personnalisé pour les familles dans les CLSC partout au Québec.",
    phone: "Contact Local CLSC / 8-1-1",
    website: "https://www.quebec.ca/famille-et-soutien-aux-personnes/enfance",
    hours: "Du lundi au vendredi",
    tags: ["Périnatalité", "Mère et Enfant", "CLSC", "Petite Enfance"],
    featured: false
  },

  // Nova Scotia & Atlantic Canada
  {
    id: "ns-811",
    province: "NS",
    provinceName: "Nova Scotia",
    category: "telehealth",
    titleEn: "811 Nova Scotia Tele-Care",
    titleFr: "811 Télé-Soins Nouvelle-Écosse",
    descEn: "Speak with registered nurses 24/7 for health triage, pediatric illness advice, and local ER wait time estimates.",
    descFr: "Parlez à des infirmiers autorisés 24/7 pour des conseils de santé et l'orientation vers les soins locaux.",
    phone: "8-1-1 (TTY: 7-1-1)",
    website: "https://811.novascotia.ca",
    hours: "24/7",
    tags: ["Nurse Line", "Atlantic", "Emergency Advice"],
    featured: true
  },
  {
    id: "ns-caregivers",
    province: "NS",
    provinceName: "Nova Scotia",
    category: "caregiver",
    titleEn: "Caregivers Nova Scotia Association",
    titleFr: "Association des aidants de la Nouvelle-Écosse",
    descEn: "Offers free support groups, individual guidance, and workshops across Nova Scotia to recognize and support unpaid caregivers.",
    descFr: "Groupes de soutien gratuits, orientation individuelle et ateliers pour les proches aidants en N.-É.",
    phone: "1-877-488-7390",
    website: "https://caregiversns.org",
    hours: "Mon-Fri 8:30am - 4:30pm AST",
    tags: ["Caregiver", "Nova Scotia", "Support Groups"],
    featured: false
  },
  {
    id: "nb-811",
    province: "NB",
    provinceName: "New Brunswick",
    category: "telehealth",
    titleEn: "Tele-Care 811 New Brunswick",
    titleFr: "Télé-Soins 811 Nouveau-Brunswick",
    descEn: "Free bilingual health advice, medical symptom assessment, and family clinic connections.",
    descFr: "Conseils de santé bilingues gratuits, évaluation des symptômes et liens vers les cliniques familiales.",
    phone: "8-1-1",
    website: "https://www2.gnb.ca/content/gnb/en/services/services_renderer.201479.Tele-Care_811.html",
    hours: "24/7 Bilingual",
    tags: ["Bilingual", "Atlantic", "Tele-Care"],
    featured: false
  },

  // Manitoba & Saskatchewan
  {
    id: "mb-healthlinks",
    province: "MB",
    provinceName: "Manitoba",
    category: "telehealth",
    titleEn: "Health Links – Info Santé Manitoba",
    titleFr: "Health Links – Info Santé Manitoba",
    descEn: "24/7 telephone health information and triage service staffed by registered nurses fluent in English and French.",
    descFr: "Service téléphonique 24/7 d'information sur la santé et d'évaluation avec infirmiers autorisés.",
    phone: "1-888-315-9257 / 204-788-8200",
    website: "https://misericordia.mb.ca/programs/phcc/health-links-info-sante/",
    hours: "24/7",
    tags: ["Nurse Line", "Manitoba", "Bilingual"],
    featured: false
  },
  {
    id: "sk-healthline",
    province: "SK",
    provinceName: "Saskatchewan",
    category: "telehealth",
    titleEn: "HealthLine 811 Saskatchewan",
    titleFr: "HealthLine 811 Saskatchewan",
    descEn: "Access registered nurses, mental health social workers, and addictions counselors with translation in over 100 languages.",
    descFr: "Accès à des infirmiers, travailleurs sociaux et conseillers en toxicomanie avec traduction en plus de 100 langues.",
    phone: "8-1-1",
    website: "https://www.saskhealthauthority.ca/your-health/healthline-811",
    hours: "24/7",
    tags: ["Nurse Line", "Mental Health", "Saskatchewan"],
    featured: false
  },

  // Territories (YT, NT, NU)
  {
    id: "yt-healthline",
    province: "YT",
    provinceName: "Yukon",
    category: "telehealth",
    titleEn: "Yukon HealthLine 811 & Community Nursing",
    titleFr: "Ligne Santé Yukon 811 et soins infirmiers",
    descEn: "Comprehensive northern health advice, remote community clinic connections, and maternal health support.",
    descFr: "Conseils santé pour le Nord, liens avec les centres de santé communautaires et soutien maternel.",
    phone: "8-1-1",
    website: "https://yukon.ca/en/health-and-wellness/health-care-services/yukon-healthline",
    hours: "24/7",
    tags: ["Territories", "Northern Health", "Remote Care"],
    featured: false
  },
  {
    id: "nt-healthline",
    province: "NT",
    provinceName: "Northwest Territories",
    category: "telehealth",
    titleEn: "NWT HealthLine (8-1-1)",
    titleFr: "Ligne Santé des TNO (8-1-1)",
    descEn: "24/7 confidential health line connecting northern families to nurse advice and fly-in clinical specialists.",
    descFr: "Ligne de santé confidentielle 24/7 reliant les familles du Nord à des infirmiers et spécialistes itinérants.",
    phone: "8-1-1",
    website: "https://www.nthssa.ca",
    hours: "24/7",
    tags: ["Northwest Territories", "Nurse Line", "Indigenous Support"],
    featured: false
  },
  {
    id: "nu-kamatsiaqtut",
    province: "NU",
    provinceName: "Nunavut",
    category: "mental",
    titleEn: "Nunavut Kamatsiaqtut Help Line",
    titleFr: "Ligne d'écoute Kamatsiaqtut du Nunavut",
    descEn: "Anonymous, confidential support line offering non-judgmental care in Inuktitut and English for families and youth across Nunavut.",
    descFr: "Ligne d'écoute anonyme et confidentielle en inuktitut et anglais pour les familles et jeunes du Nunavut.",
    phone: "1-800-265-3333 / 867-979-3333",
    website: "http://www.nunavuthelpline.ca",
    hours: "24/7",
    tags: ["Inuktitut", "Nunavut", "Mental Health", "Northern Care"],
    featured: false
  }
];

window.provincialDirectory = provincialDirectory;
